version: '2.2'
services: 
    PSQL:
        image: postgres
        container_name: teamcity-postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: password #set your password 
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes: 
            - /opt/teamcity/postgresql/data:/var/lib/postgresql/data
        networks:
          - teamcity-network
    TeamCity:
        image: teamcity-server
        container_name: teamcity-server
        restart: always
        ports: 
            - "8111:8111"
        volumes: 
            - /opt/teamcity/data:/data/teamcity_server/datadir
            - /opt/teamcity/logs:/opt/teamcity/logs
        networks:
          - teamcity-network
        cpus: '2'
    TeamCityAgent:
        image: teamcity-agent
        container_name: teamcity-agent
        restart: always
        environment:
          - SERVER_URL=http://TeamCity:8111
          - AGENT_NAME=regular_agent
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/teamcity/agent/conf:/data/teamcity_agent/conf
        networks:
          - teamcity-network
networks:
  teamcity-network:
    driver: bridge
