version: '2.2'
services: 
    PSQL:
        image: postgres
        container_name: teamcity-postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: password #set your password 
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes: 
            - /opt/teamcity/postgresql/data:/var/lib/postgresql/data
        networks:
          - teamcity-network
    teamcity-server:
        image: teamcity-server
        container_name: teamcity-server
        restart: always
        ports: 
            - "8111:8111"
        volumes: 
            - /opt/teamcity/data:/data/teamcity_server/datadir
            - /opt/teamcity/logs:/opt/teamcity/logs
        networks:
          - teamcity-network
        cpus: '2' #number of max cpus, if not the server use 100% of cpus at start for several minutes
    teamcity-agent-docker:
        image: teamcity-agent-docker
        container_name: teamcity-agent-docker
        restart: always
        user: '0' #user uid, 0 for root user
        environment:
          - SERVER_URL=http://teamcity-server:8111/
          - AGENT_NAME=regular_docker_agent
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - teamcity-network
        depends_on:
          - teamcity-server
networks:
  teamcity-network:
    driver: bridge
